[meta]
save_dir = "exp"
description = "Train a model using Generative Adversarial Networks (GANs)"
seed = 20220815

[trainer]
path = "trainer.Trainer"
[trainer.args]
debug = false
max_steps = 0
max_epochs = 200
max_grad_norm = 10
save_max_score = true
save_ckpt_interval = 10
max_patience = 20
plot_norm = true
validation_interval = 10
max_num_checkpoints = 20
scheduler_name = "constant_schedule_with_warmup"
warmup_steps = 0
warmup_ratio = 0.00
gradient_accumulation_steps = 1

[loss_function]
path = "torch.nn.MSELoss"
[loss_function.args]

[optimizer]
path = "torch.optim.AdamW"
[optimizer.args]
lr = 1e-3

[model]
path = "audiozen.models.cirm_gsn.modeling_cirm_gsn.Model"
[model.args]
n_fft = 512
hop_length = 128
win_length = 512
fdrc = 0.5
input_size = 257
hidden_size = 268
num_layers = 4
proj_size = 257
output_activate_function = false
df_order = 3
use_pre_layer_norm_fb = true
bn = true
shared_weights = true
sequence_model = "GSN"
num_spks = 1

[acoustics]
n_fft = 512
hop_length = 128
win_length = 512
sr = 16000

[train_dataset]
path = "dataloader.DNSAudio"
[train_dataset.args]
root = "/datasets/datasets_fullband/training_set/"
limit = false
offset = 0
[train_dataset.dataloader]
batch_size = 64
num_workers = 8
drop_last = true
pin_memory = true

[validate_dataset]
path = "dataloader.DNSAudio"
[validate_dataset.args]
root = "/datasets/datasets_fullband/validation_set/"
train = false
[validate_dataset.dataloader]
batch_size = 1
num_workers = 0

[test_dataset]
path = "dataloader.DNSAudio"
[test_dataset.args]
root = "/nfs/xhao/data/intel_ndns/test_set/"
train = false
[test_dataset.dataloader]
batch_size = 1
num_workers = 0
